[server]
port = 3000

[server.rate_limit]
enabled = true
requests_per_second = 10
burst_size = 10

[database]
url = "postgres://postgres:postgres@localhost:5432/crypto_wallets"

[vault]
address = "http://localhost:8200"
token = "root"
key_id = "wallet-master-key"
